server.port: 5001

spring:
  application.name: product-service
  datasource:
    url: jdbc:postgresql://dedilemma-product-service-db:5432/product_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect

eureka.client.serviceUrl:
  defaultZone: http://dedilemma-discovery-server:5555/eureka/
