server.port: 5002

spring:
  application.name: rating-service
  datasource:
    url: jdbc:postgresql://dedilemma-rating-service-db:5432/rating_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect

eureka.client.serviceUrl:
  defaultZone: http://dedilemma-discovery-server:5555/eureka/
