server.port: 5002

spring:
  application.name: rating-service
  datasource:
    url: jdbc:postgresql://rating-service-db:5432/rating_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: none
    show-sql: true

eureka.client.serviceUrl:
  defaultZone: http://discovery-server:5555/eureka/
